service: serverless-nestjs

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev
  environment:
    NODE_ENV: ${self:provider.stage}
    ORDERS_TABLE: OrdersTable
    USERS_TABLE: UsersTable
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:GetItem
            - dynamodb:Query
          Resource:
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.ORDERS_TABLE}
            - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.USERS_TABLE}

package:
  patterns:
    - '!node_modules/**'

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: '/{proxy+}'
      - http:
          method: ANY
          path: '/'

custom:
  serverless-offline:
    noPrependStageInUrl: true

resources:
  Resources:
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.ORDERS_TABLE}
        AttributeDefinitions:
          - AttributeName: orderId
            AttributeType: 'S'
          - AttributeName: userId
            AttributeType: 'S'
        KeySchema:
          - AttributeName: orderId
            KeyType: 'HASH'
        GlobalSecondaryIndexes:
          - IndexName: UserIdIndex
            KeySchema:
              - AttributeName: userId
                KeyType: 'HASH'
            Projection:
              ProjectionType: 'ALL'
        BillingMode: PAY_PER_REQUEST

    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: EmailIndex
            KeySchema:
              - AttributeName: email
                KeyType: 'HASH'
            Projection:
              ProjectionType: 'ALL'
        BillingMode: PAY_PER_REQUEST
